@contentType = application/json

#######################################
### Request: DELETE /api/Product/{id}
#######################################

### Path Parameter: id
@id = 0


DELETE http://localhost:5000/api/Product/{{id}}
Content-Type: {{contentType}}


