@contentType = application/json

####################################
### Request: GET /api/Product/{id}
####################################

### Path Parameter: id
@id = 0


GET http://localhost:5000/api/Product/{{id}}
Content-Type: {{contentType}}


